using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Stopwatch.SourceGenerators;

[Generator]
public class PackageInfoGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find the Directory.Packages.props file
		var packagesPropsFile = context.AdditionalTextsProvider
			.Where(file => file.Path.EndsWith("Directory.Packages.props"));

		// Generate the source code
		context.RegisterSourceOutput(packagesPropsFile, (spc, file) =>
		{
			var packages = ParsePackagesProps(file);
			var source = GenerateSource(packages);
			spc.AddSource("GeneratedPackageInfo.g.cs", SourceText.From(source, Encoding.UTF8));
		});
	}

	private static List<PackageInfo> ParsePackagesProps(AdditionalText file)
	{
		var packages = new List<PackageInfo>();
		var content = file.GetText()?.ToString();
		if (string.IsNullOrEmpty(content))
		{
			return packages;
		}

		try
		{
			var doc = XDocument.Parse(content);
			var packageVersions = doc.Descendants("PackageVersion");

			foreach (var packageVersion in packageVersions)
			{
				var name = packageVersion.Attribute("Include")?.Value;
				var version = packageVersion.Attribute("Version")?.Value;

				if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(version))
				{
					// Filter out internal/build-only packages
					if (!ShouldIncludePackage(name))
					{
						continue;
					}

					packages.Add(new PackageInfo
					{
						Name = name,
						Version = version,
						Url = $"https://www.nuget.org/packages/{name}"
					});
				}
			}
		}
		catch
		{
			// If parsing fails, return empty list
		}

		return packages;
	}

	private static bool ShouldIncludePackage(string packageName)
	{
		// Exclude internal/build-only packages
		var excludedPrefixes = new[]
		{
			"Microsoft.SourceLink",
			"System.Private",
			"System.Text.Json" // This is typically included by the framework
		};

		foreach (var prefix in excludedPrefixes)
		{
			if (packageName.StartsWith(prefix))
			{
				return false;
			}
		}

		return true;
	}

	private static string GenerateSource(List<PackageInfo> packages)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine();
		sb.AppendLine("namespace Stopwatch.Dialogs;");
		sb.AppendLine();
		sb.AppendLine("public static class GeneratedPackageInfo");
		sb.AppendLine("{");
		sb.AppendLine("    public static List<PackageInfo> GetPackages()");
		sb.AppendLine("    {");
		sb.AppendLine("        return new List<PackageInfo>");
		sb.AppendLine("        {");

		foreach (var package in packages)
		{
			var escapedName = EscapeString(package.Name);
			var escapedVersion = EscapeString(package.Version);
			var escapedUrl = EscapeString(package.Url);
			sb.AppendLine($"            new PackageInfo(\"{escapedName}\", \"{escapedVersion}\", \"{escapedUrl}\"),");
		}

		sb.AppendLine("        };");
		sb.AppendLine("    }");
		sb.AppendLine("}");

		return sb.ToString();
	}

	private static string EscapeString(string value)
	{
		return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
	}

	private class PackageInfo
	{
		public string Name { get; set; } = "";
		public string Version { get; set; } = "";
		public string Url { get; set; } = "";
	}
}
