<Project Sdk="Uno.Sdk">
	<PropertyGroup>
		<TargetFrameworks>
			net9.0-windows10.0.26100;
			net9.0-android;
			net9.0-ios;
			net9.0-desktop;
			net9.0-browserwasm;
		</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<UnoSingleProject>true</UnoSingleProject>

		<!-- Display name -->
		<ApplicationTitle>Fluent Stopwatch</ApplicationTitle>
		<!-- App Identifier -->
		<ApplicationId>dev.mzikmund.stopwatch</ApplicationId>
		<!-- Versions -->
		<ApplicationDisplayVersion>0.8.9</ApplicationDisplayVersion>
		<ApplicationVersion>14</ApplicationVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<UnoFeatures>
			Hosting;
			Mvvm;
			Localization;
			ThemeService;
			SkiaRenderer;
			Skia;
		</UnoFeatures>

		<UnoIconBackgroundFile>Assets/Icons/icon_transparent.svg</UnoIconBackgroundFile>
		<UnoIconBackgroundFile Condition="'$(IsIOS)' == 'true' or '$(IsAndroid)' == 'true'">Assets/Icons/icon.svg</UnoIconBackgroundFile>

		<UnoIconForegroundScale>1</UnoIconForegroundScale>
		<UnoIconForegroundScale Condition="'$(IsAndroid)' == 'true'">0.65</UnoIconForegroundScale>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net9.0-browserwasm'">
		<WasmShellEnableIDBFS>true</WasmShellEnableIDBFS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" />
		<PackageReference Include="CommunityToolkit.WinUI.Helpers" />
		<PackageReference Include="LiteDB" Condition="'!$(IsIOS)' and !'$(IsAndroid)'" />
		<PackageReference Include="MZikmund.Toolkit.WinUI" />
		<PackageReference Include="Plugin.InAppBilling" />
	</ItemGroup>
</Project>

