name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**

env:
  STEP_TIMEOUT_MINUTES: 60

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  smoke_test:
    name: Smoke Test (Debug Build of Fluent Stopwatch)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache NuGet to speed up restores
      - name: NuGet cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sln*', '**/*.csproj', '**/Directory.Packages.props', '**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-          

      - name: Setup .NET SDK 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install .NET workloads
        run:
          dotnet workload restore "$Solution_Fullname"

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Stopwatch (Debug)
        shell: pwsh
        run: msbuild ./src/Stopwatch/Stopwatch.csproj /r
